export const API_URL_TYPE = {
  ALBUS_ADMIN_USER_SEARCH_LIST: "ALBUS_ADMIN_USER_SEARCH_LIST",
  CUSTOMER_ACCOUNT_SEARCH: "CUSTOMER_ACCOUNT_SEARCH",
  CUSTOMER_ACCOUNT_SEARCH_DETAIL: "CUSTOMER_ACCOUNT_SEARCH_DETAIL",
  CUSTOMER_ACCOUNT_DETAILS: "CUSTOMER_ACCOUNT_DETAILS",
  CUSTOMER_ACCOUNT_UPDATE: "CUSTOMER_ACCOUNT_UPDATE",
  CUSTOMER_ACCOUNT_TIMEZONE: "CUSTOMER_ACCOUNT_TIMEZONE",
  CUSTOMER_ACCOUNT_DUP_IATA: "CUSTOMER_ACCOUNT_DUP_IATA",
  PERSONAL_INFO: "PERSONAL_INFO",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  COMMON: {
    TIMEZONE: "COMMON_TIMEZONE",
    PROVIDER_GRP: "COMMON_PROVIDER_GRP",
    AIRLINE: "COMMON_AIRLINE",
  },
  AGGREGATOR: {
    HALO_CREDENTIAL: {
      SEARCH: "AGGREGATOR_HALO_CREDENTIAL_SEARCH",
    },
    HALO_AIRLINE_CONTROL: {
      SEARCH: "AGGREGATOR_HALO_AIRLINE_CONTROL_SEARCH",
      CHANGE_HISTORY: "AGGREGATOR_HALO_AIRLINE_CONTROL_CHANGE_HISTORY",
    },
    PROVIDER_AIRLINE: {
      SEARCH: "AGGREGATOR_PROVIDER_AIRLINE_SEARCH",
      DETAILS: "AGGREGATOR_PROVIDER_AIRLINE_DETAILS",
    },
  },
  ACCOUNT: {
    LUNA_ADMIN: {
      SEARCH_LIST: "ACCOUNT_LUNA_ADMIN_SEARCH_LIST",
      ADD: "ACCOUNT_LUNA_ADMIN_ADD",
      DETAIL: "ACCOUNT_LUNA_ADMIN_DETAIL",
      UPDATE: "ACCOUNT_LUNA_ADMIN_UPDATE",
      DELETE: "ACCOUNT_LUNA_ADMIN_DELETE",
      ACCOUNT_LIST: "ACCOUNT_LUNA_ADMIN_ACCOUNT_LIST",
    },
  },
  ANALYZE: {
    DETECTION: {
      SERVERS: "ANALYZE_DETECTION_SERVERS",
      CLUSTERS: "ANALYZE_DETECTION_CLUSTERS",
      MANAGERS: "ANALYZE_DETECTION_MANAGERS",
      CLUSTER_CHECK: "ANALYZE_DETECTION_CLUSTER_CHECK",
      ASSIGN_CLUSTER: "ANALYZE_DETECTION_ASSIGN_CLUSTER",
      ASSIGN_MANAGER: "ANALYZE_DETECTION_ASSIGN_MANAGER",
    },
  },
};
